### PR TITLE
added check to see if 'content-type' is set

### PR DESCRIPTION
**Pull request by G3z**
this prevents server crashes if requests are sent with an empty body
like:
jQuery.post("http://localhost:3000/comments/",{},function(data){
   console.log(data)
});

### CODE REVIEW

**Comment by kilianc** [comment]
Thanks @G3z for pointing out this issue.
However, I can't merge this because test is missing and also, I don't think this is the right way to fix it.

Could you post the crash stack?

**Comment by G3z** [comment]
sure thing:
.../node_modules/apiserver/lib/middleware/payload-parser.js:15
      if (request.headers['content-type'].match(/application\/x-www-form-urlen
                                          ^
TypeError: Cannot call method 'match' of undefined
    at IncomingMessage.module.exports (/Users/g3z/Sites/flowments/dam/node_modules/apiserver/lib/middleware/payload-parser.js:15:43)
    at IncomingMessage.g (events.js:192:14)
    at IncomingMessage.EventEmitter.emit (events.js:126:20)
    at IncomingMessage.self.emit (/Users/g3z/Sites/flowments/dam/node_modules/apiserver/node_modules/buffered-request/lib/buffered-request.js:45:17)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete](http.js:149:23)
    at Socket.socket.ondata (http.js:1704:22)
    at TCP.onread (net.js:403:27)

**Comment by kilianc** [comment]
Thanks.

So, if you add the test and you change the code this way, I'll merge:

``` js

if (!request.headers['content-type']) return
```

Right before the first `if` statement.

n.b. I didn't check for _undefinedness_ just because it has to return anyway, even with an empty `content-type`

Thanks again.

**Comment by kilianc** [comment]
I'll look into it this weekend. Looks good so far. :+1:

**Pull request merged**
